server:
  port: 8081
  servlet:
    context-path: /flowManager
spring:
  application:
    name: flow-manager
  datasource:
    url: jdbc:mysql://localhost:3306/eir1?useSSL=false&allowPublicKeyRetrieval=true
    username: eir
    password: Eir@1234
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  jpa:
    #properties:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG

eir:
  udp:
    server:
      port: 7001